spring:
  datasource:
    driverClassName: org.h2.Driver
    url: jdbc:h2:mem:mentorship;MODE=PostgreSQL
    data: classpath:/db/data.sql
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create
    repositories:
      enabled: true